"""Loading the five tables that hang off ``users``.

Order matters and is not alphabetical: every table here has a foreign key to
``users``, so the user load runs first and its ids are read back once into a map.
Nothing in this file invents an id.

All five run inside the caller's transaction and inside
``timestamps_from_source``, so Bubble's ``created_at``/``updated_at`` survive the
same way they do for ``users`` — and a failure rolls the whole phase back
together rather than leaving four tables loaded and one not.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from uuid import UUID

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncConnection

from app.domain.resolve import Resolution
from app.domain.transform import AdminGrantRow, IdentityRow, OnboardingRow, ProfileRow

UPSERT_PROFILE = """
INSERT INTO user_profiles (
    user_id, legacy_bubble_id, created_at, updated_at, avatar_url, banner_url,
    about_me, gender, origin_country_id, social_linkedin, social_twitter,
    social_youtube, email_provider_contact_id
) VALUES (
    :user_id, :legacy_bubble_id, :created_at, :updated_at, :avatar_url, :banner_url,
    :about_me, :gender, :origin_country_id, :social_linkedin, :social_twitter,
    :social_youtube, :email_provider_contact_id
)
ON CONFLICT (legacy_bubble_id) DO UPDATE SET
    user_id                   = EXCLUDED.user_id,
    created_at                = EXCLUDED.created_at,
    updated_at                = EXCLUDED.updated_at,
    avatar_url                = EXCLUDED.avatar_url,
    banner_url                = EXCLUDED.banner_url,
    about_me                  = EXCLUDED.about_me,
    gender                    = EXCLUDED.gender,
    origin_country_id         = EXCLUDED.origin_country_id,
    social_linkedin           = EXCLUDED.social_linkedin,
    social_twitter            = EXCLUDED.social_twitter,
    social_youtube            = EXCLUDED.social_youtube,
    email_provider_contact_id = EXCLUDED.email_provider_contact_id
"""

# `user_languages` has no `legacy_bubble_id` — it is derived from a column of the
# PersonalInfo row rather than from its own Bubble Thing (settled decision #27),
# so its idempotency key is the natural pair the unique index already enforces.
UPSERT_LANGUAGE = """
INSERT INTO user_languages (user_id, language_id, is_primary)
VALUES (:user_id, :language_id, false)
ON CONFLICT (user_id, language_id) DO NOTHING
"""

UPSERT_ONBOARDING = """
INSERT INTO user_onboarding (user_id, last_step, completed_at)
VALUES (:user_id, :last_step, :completed_at)
ON CONFLICT (user_id) DO UPDATE SET
    last_step    = EXCLUDED.last_step,
    completed_at = EXCLUDED.completed_at
"""

UPSERT_IDENTITY = """
INSERT INTO auth_identities (user_id, provider, provider_user_id)
VALUES (:user_id, :provider, :provider_user_id)
ON CONFLICT (provider, provider_user_id) DO UPDATE SET
    user_id = EXCLUDED.user_id
"""

# Only where no live grant exists. A revoked grant stays, and a re-run must not
# create a second live one — which the partial unique index would reject anyway,
# turning a repeated load into a failure instead of a no-op.
# No `CAST(... AS admin_role)` any more: settled decision #100 made the column
# `text` + `CHECK`, and the cast named a type that no longer exists. The guarantee
# did not weaken — `ck_admin_users_admin_role_is_known` refuses an unknown value
# from this statement exactly as the enum did, and this is the path that needs it,
# since the loader writes raw SQL and never builds a model.
UPSERT_ADMIN = """
INSERT INTO admin_users (user_id, admin_role)
SELECT :user_id, :admin_role
WHERE NOT EXISTS (
    SELECT 1 FROM admin_users
    WHERE user_id = :user_id
      AND admin_role = :admin_role
      AND revoked_at IS NULL
)
"""


@dataclass(frozen=True, slots=True)
class SatelliteCounts:
    profiles: int = 0
    languages: int = 0
    onboarding: int = 0
    identities: int = 0
    admin_grants: int = 0
    languages_skipped: tuple[str, ...] = ()
    countries_skipped: tuple[str, ...] = ()


async def user_id_map(connection: AsyncConnection) -> dict[str, UUID]:
    """``legacy_bubble_id`` to ``users.id``, read back after the user load.

    Read rather than remembered: the loader upserts, so on a re-run the ids
    already exist and were not generated by this process. Carrying ids forward
    from the insert would work on a first run and silently produce nothing on
    every subsequent one.
    """
    result = await connection.execute(
        text("SELECT legacy_bubble_id, id FROM users WHERE legacy_bubble_id IS NOT NULL")
    )
    return {row.legacy_bubble_id: row.id for row in result}


class SatelliteLoader:
    """The five tables that hang off ``users``."""

    def __init__(self, connection: AsyncConnection) -> None:
        self._connection = connection

    async def load(
        self,
        *,
        users: dict[str, UUID],
        profiles: Sequence[ProfileRow],
        onboarding: Sequence[OnboardingRow],
        identities: Sequence[IdentityRow],
        admin_grants: Sequence[AdminGrantRow],
        countries: Resolution,
        languages: Resolution,
    ) -> SatelliteCounts:
        profile_count = 0
        language_count = 0
        skipped_languages: set[str] = set()
        skipped_countries: set[str] = set()

        for profile in profiles:
            user_id = users.get(profile.user_bubble_id)
            if user_id is None:
                # Cannot happen if the user load ran first and reconciled; a
                # foreign key would catch it anyway. Skipping silently is what
                # must not happen, so this raises.
                raise LookupError(
                    f"profile {profile.legacy_bubble_id} references unknown user "
                    f"{profile.user_bubble_id}"
                )

            country_id = None
            if profile.origin_country_name:
                if profile.origin_country_name in countries:
                    country_id = countries[profile.origin_country_name]
                else:
                    # The row still loads, without a country. A country that did
                    # not resolve is reported by name so somebody can add an
                    # alias; dropping the whole profile over it would lose the
                    # bio, avatar and socials as well.
                    skipped_countries.add(profile.origin_country_name)

            await self._connection.execute(
                text(UPSERT_PROFILE),
                {
                    "user_id": user_id,
                    "legacy_bubble_id": profile.legacy_bubble_id,
                    "created_at": profile.created_at,
                    "updated_at": profile.updated_at,
                    "avatar_url": profile.avatar_url,
                    "banner_url": profile.banner_url,
                    "about_me": profile.about_me,
                    "gender": profile.gender,
                    "origin_country_id": country_id,
                    "social_linkedin": profile.social_linkedin,
                    "social_twitter": profile.social_twitter,
                    "social_youtube": profile.social_youtube,
                    "email_provider_contact_id": profile.email_provider_contact_id,
                },
            )
            profile_count += 1

            for name in profile.language_names:
                if name not in languages:
                    skipped_languages.add(name)
                    continue
                await self._connection.execute(
                    text(UPSERT_LANGUAGE),
                    {"user_id": user_id, "language_id": languages[name]},
                )
                language_count += 1

        onboarding_count = 0
        for row in onboarding:
            await self._connection.execute(
                text(UPSERT_ONBOARDING),
                {
                    "user_id": users[row.user_bubble_id],
                    "last_step": row.last_step,
                    "completed_at": row.completed_at,
                },
            )
            onboarding_count += 1

        identity_count = 0
        for identity in identities:
            await self._connection.execute(
                text(UPSERT_IDENTITY),
                {
                    "user_id": users[identity.user_bubble_id],
                    "provider": identity.provider.value,
                    "provider_user_id": identity.provider_user_id,
                },
            )
            identity_count += 1

        admin_count = 0
        for grant in admin_grants:
            await self._connection.execute(
                text(UPSERT_ADMIN),
                {"user_id": users[grant.user_bubble_id], "admin_role": grant.admin_role.value},
            )
            admin_count += 1

        return SatelliteCounts(
            profiles=profile_count,
            languages=language_count,
            onboarding=onboarding_count,
            identities=identity_count,
            admin_grants=admin_count,
            languages_skipped=tuple(sorted(skipped_languages)),
            countries_skipped=tuple(sorted(skipped_countries)),
        )


async def reference_maps(connection: AsyncConnection) -> tuple[dict[str, UUID], dict[str, UUID]]:
    """Display name to id, for ``countries`` and ``languages``.

    Built by querying rather than hard-coded, because reference ids are
    generated per environment (ADR 0015) — a literal would be correct in one
    database and silently wrong in every other.
    """
    countries = await connection.execute(text("SELECT display_name, id FROM countries"))
    languages = await connection.execute(text("SELECT display_name, id FROM languages"))
    return (
        {row.display_name: row.id for row in countries},
        {row.display_name: row.id for row in languages},
    )
