"""The migration chain itself.

Every test here runs against a database created for it and dropped afterwards,
and every one is synchronous: ``migrations/env.py`` calls ``asyncio.run``, which
raises ``RuntimeError`` if a loop is already running.
"""

import asyncio
from collections.abc import Callable
from pathlib import Path
from typing import Any

import asyncpg
import pytest
from alembic import command
from alembic.config import Config

from app.domain.meetings import PLATFORM_DEFAULT_PROVIDER

pytestmark = pytest.mark.db

#: Every function the chain creates, at head — the exact set, not a count.
#:
#: This is the **only** guard on a function's name.
#: `test_every_schema_identifier_appears_verbatim_in_source` collects constraint
#: names, index names and enum type names; functions are in none of those, so
#: nothing else in the gate notices one renamed, dropped or added.
#:
#: `apply_mentor_status` was absent from this tuple for two phases — M2 created
#: it and the assertion was a count over a hard-coded list, which could not see
#: it. `timerange` and `timemultirange` are generated by M3's `CREATE TYPE ... AS
#: RANGE` rather than written out; they are ours, and they are dropped with the
#: type. `session_window` joins in M4 (`d7c31f8a2b45`).
#:
#: `refuse_retiring_a_primary_offering` joined in `d5a83b17c9e4` and **left in
#: `c8f1a3e2b904`**, with `mentor_profiles.primary_session_type_id`. It was the
#: only **business-rule** function here — every remaining entry is
#: infrastructure — and it existed because `ON DELETE RESTRICT` cannot see a
#: retirement that happens as `deleted_at` or `is_active = false`, both UPDATEs.
#: With nothing pointing at a session type there is nothing for it to protect.
#: `tests/integration/test_offering_retirement.py` asserts its absence directly,
#: because this tuple would also pass against a trigger left in place over a
#: dropped function.
#:
#: `log_availability_change` joins in `5930c3cc1109` (ADR 0029): the trigger
#: function that logs a change to a mentor's availability, so the card stops
#: vouching for a stored next free time. Infrastructure like the rest — it
#: decides nothing, it only invalidates a cache.
#:
#: This tuple catching a *new* one is the test doing its job: a schema-level
#: object added without a downgrade would survive `downgrade base` and break the
#: next upgrade on "already exists", which is exactly what the assertion above
#: the re-upgrade is for.
FUNCTION_NAMES = (
    "apply_mentor_status",
    "clear_stale_avatar_focus",
    "log_availability_change",
    "session_window",
    "set_updated_at",
    "timemultirange",
    "timerange",
    "uuid_generate_v7",
)

# Extensions the chain is expected to install, at head.
#
# `citext` is deliberately absent: M1 created it for `users.email` and
# `e25541374c03` dropped it again when normalisation moved to the boundary. The
# chain still creates and drops it in between, which is why this asserts the
# state at head rather than every extension the chain has ever touched.
# `pg_trgm` is the first extension whose *operators* the schema depends on:
# `pgcrypto` was declared for tidiness but `gen_random_uuid()` has been core
# since PostgreSQL 13, so a missing pgcrypto would never have surfaced. A missing
# pg_trgm fails loudly at `CREATE INDEX ... USING gin (name gin_trgm_ops)`.
#
# `btree_gist` joins them in M3 and is load-bearing in the same way: uuid has no
# GiST operator class without it, so `ix_availability_exceptions_range` cannot be
# built at all. It is the one extension the chain creates with `IF NOT EXISTS`,
# because Supabase already has it installed while the local and CI containers do
# not — and unlike the others it is never dropped on downgrade.
EXTENSION_NAMES = ("btree_gist", "pg_trgm", "pgcrypto")

# The exact set of tables at head, in the order `table_names` returns them.
#
# Asserting the exact list rather than a subset is what catches the reverse
# mistake: a table dropped, renamed, or never created because a migration was
# written but not added to the chain. It has to be updated in the same change
# that adds a table, which is the point — the same discipline as EXPECTED_MODELS
# in tests/unit/test_models.py.
EXPECTED_TABLES = [
    # M0 — reference data
    "countries",
    "languages",
    # M1 — identity
    "admin_users",
    "auth_identities",
    "legal_documents",
    "user_languages",
    "user_legal_consents",
    "user_onboarding",
    "user_profiles",
    "users",
    # M2 — the four lookups the profile tables reference
    "degree_levels",
    "institutions",
    "reviews",
    "scholarship_programs",
    "service_offerings",
    # M2 — the profile tables themselves. `user_scholarship_experience` is
    # deliberately absent: no option set, no values, nothing to write it.
    "education_entries",
    "featured_mentors",
    "mentee_goal_countries",
    "mentee_goal_needs",
    "mentee_goals",
    "mentor_conferencing_options",
    "mentor_availability_changes",
    "mentor_next_availability",
    "mentor_profiles",
    "mentor_service_offerings",
    "mentor_status_events",
    "user_awards",
    # M3 — availability. `calendar_connections` is deliberately absent: nothing
    # in M3 reads or writes it, and settled decision #21 ships it with the phase
    # that first needs it. See the M3 migration's docstring.
    "availability_exceptions",
    "availability_rules",
    # Deferred since M1 by two migrations that each said so, and arriving with
    # the free/busy read that needs it.
    "calendar_connections",
    # M4 — per-offering windows, which replace general availability for the
    # offering that has them. Listed with M4 rather than M3 because they are
    # a property of an offering.
    "session_type_scheduling_windows",
    # M4 — sessions. The four intake tables were deferred out of this phase and
    # have since landed, listed below. `session_notes` is still absent, for the
    # reason that deferred all five: no legacy source, no read surface, and
    # settled decision #21 ships a table with the phase that first needs it.
    # `calendar_connections` is still absent for the reason M3 recorded, now
    # joined by a second: the calendar integration goes direct to the Google API
    # rather than through Composio, so the columns encoding a Composio reference
    # are the wrong shape. See the M4 migration's docstring.
    "session_events",
    "session_participants",
    "session_type_booking_configs",
    # Session Types #9: the offerings one session type covers, up to three.
    "session_type_offerings",
    # Session Types round 3 A (#215): the stages one session type is aimed at.
    "session_type_stages",
    "session_types",
    "sessions",
    # M4 — the intake stack, deferred out of `04_sessions.sql` when M4 shipped
    # and landing whole. `session_type_question_options` has no writer yet; see
    # its model for why shipping it early is now cheap.
    "intake_answers",
    "intake_files",
    "intake_submissions",
    "session_type_question_options",
    "session_type_questions",
    # M4 — platform infrastructure, which serves every feature and belongs to
    # none. First of the three in `08_features_platform.sql`; `outbox_events`
    # and `feature_flags` ship with whatever first needs them (#21).
    "idempotency_keys",
    "outbox_events",
    # M5b — the credit ledger. Two tables, no writer yet: PR 1 lands the shape
    # so the vocabularies and the two partial indexes are settled before
    # anything can depend on them.
    "admin_credit_grants",
    "credit_lots",
    "credit_transactions",
    # M6 — review moderation.
    "review_reports",
    # M5b PR 2 — the invite and the once-only gate it opens.
    "referrals",
    "referral_unlocks",
]

# **No enum types at head, and that is settled decision #100 completed.**
#
# This tuple used to name every type the chain created, because a type outlives
# the table that used it: `DROP TABLE` does not remove one, so a downgrade that
# forgets leaves an orphan and the next upgrade fails on "already exists". Eight
# migrations converted all seventeen to `text` + `CHECK`, ending with
# `session_status` in `d3a6f81b52c7`.
#
# Empty is an assertion, not an absence of one: `enum_type_names(db) == []` fails
# the moment a migration creates a type. That is the regression to guard — the
# deferred `calendar_connections` and `search_impressions_suppressed` tables both
# declare enums in the canonical DDL, and building either verbatim would
# reintroduce one while every other gate stayed green.
ENUM_TYPE_NAMES: tuple[str, ...] = ()

ConfigFactory = Callable[[str], Config]


def scalar(url: str, sql: str) -> Any:
    async def _run() -> Any:
        conn = await asyncpg.connect(url)
        try:
            return await conn.fetchval(sql)
        finally:
            await conn.close()

    return asyncio.run(_run())


def execute(url: str, sql: str) -> None:
    """Mirrors `scalar`, for statements that return nothing."""

    async def _run() -> None:
        conn = await asyncpg.connect(url)
        try:
            await conn.execute(sql)
        finally:
            await conn.close()

    asyncio.run(_run())


def function_names(url: str) -> list[str]:
    """Every function **we** created, asked of the database rather than named.

    This was a count over a hard-coded name list, and that shape cannot fail in
    the direction that matters. Deriving the SQL from ``FUNCTION_NAMES`` made it
    strictly worse — the query then counted exactly the functions it named, so
    ``count == len(FUNCTION_NAMES)`` became a tautology. `session_window` was
    added, the tuple was not updated, and the assertion **passed**.

    Asking the schema instead caught something the count had hidden for two
    phases: ``apply_mentor_status`` — the function behind
    ``trg_apply_mentor_status``, which projects mentor status events onto their
    columns — had never been registered at all.

    Extension members are excluded through ``pg_depend``; `btree_gist`,
    `pg_trgm` and `pgcrypto` install into `public` and their functions are not
    ours. ``timerange`` and ``timemultirange`` *are* ours, generated by M3's
    ``CREATE TYPE ... AS RANGE`` rather than written by hand — distinct names, so
    the several arities of each collapse to one entry.
    """

    async def _run() -> list[str]:
        conn = await asyncpg.connect(url)
        try:
            rows = await conn.fetch(
                "SELECT DISTINCT p.proname FROM pg_proc p "
                "JOIN pg_namespace n ON n.oid = p.pronamespace "
                "WHERE n.nspname = 'public' AND NOT EXISTS ("
                "  SELECT 1 FROM pg_depend d WHERE d.objid = p.oid AND d.deptype = 'e') "
                "ORDER BY 1"
            )
            return [row["proname"] for row in rows]
        finally:
            await conn.close()

    return asyncio.run(_run())


def has_pgcrypto(url: str) -> bool:
    return scalar(url, "SELECT 1 FROM pg_extension WHERE extname = 'pgcrypto'") == 1


def extension_names(url: str) -> list[str]:
    """The extensions this project installs, by name.

    Returns names rather than a count, and filters in Python rather than in an
    interpolated ``IN`` list: a count tells you something is missing, a name
    tells you which. The query itself takes no input, so there is no string
    building to get wrong.
    """

    async def _run() -> list[str]:
        conn = await asyncpg.connect(url)
        try:
            rows = await conn.fetch("SELECT extname FROM pg_extension ORDER BY extname")
            return [row["extname"] for row in rows if row["extname"] in EXTENSION_NAMES]
        finally:
            await conn.close()

    return asyncio.run(_run())


def enum_type_names(url: str) -> list[str]:
    """Enum types in the public schema, whether or not any table still uses one.

    Deliberately not scoped to types a column references — an orphaned type is
    exactly the failure being watched for, and scoping the query that way would
    make it invisible.
    """

    async def _run() -> list[str]:
        conn = await asyncpg.connect(url)
        try:
            rows = await conn.fetch(
                "SELECT t.typname FROM pg_type t "
                "JOIN pg_namespace n ON n.oid = t.typnamespace "
                "WHERE t.typtype = 'e' AND n.nspname = 'public' ORDER BY t.typname"
            )
            return [row["typname"] for row in rows]
        finally:
            await conn.close()

    return asyncio.run(_run())


def table_names(url: str) -> list[str]:
    async def _run() -> list[str]:
        conn = await asyncpg.connect(url)
        try:
            rows = await conn.fetch(
                "SELECT tablename FROM pg_tables "
                "WHERE schemaname = 'public' AND tablename <> 'alembic_version' "
                "ORDER BY tablename"
            )
            return [row["tablename"] for row in rows]
        finally:
            await conn.close()

    return asyncio.run(_run())


def test_chain_applies_to_an_empty_database(
    disposable_database: str, make_alembic_config: ConfigFactory
) -> None:
    """From empty, not from wherever the developer's database happens to be.

    A chain that only runs from the current revision is broken for every new
    environment, and nothing reveals that until someone tries to provision one.
    """
    command.upgrade(make_alembic_config(disposable_database), "head")

    assert has_pgcrypto(disposable_database)
    assert extension_names(disposable_database) == sorted(EXTENSION_NAMES)
    assert function_names(disposable_database) == sorted(FUNCTION_NAMES)
    assert sorted(table_names(disposable_database)) == sorted(EXPECTED_TABLES)
    assert enum_type_names(disposable_database) == sorted(ENUM_TYPE_NAMES)


def test_models_and_the_chain_agree(
    migrated_database: str, make_alembic_config: ConfigFactory
) -> None:
    """``alembic check`` — the drift detector that only exists once models do.

    It compares the models against the schema the chain actually produced, and
    raises ``AutogenerateDiffsDetected`` when they disagree. Before PR 2 this
    passed trivially: with no models the metadata was empty, so there was nothing
    to differ. A check that cannot fail is not a check, which is why it arrives
    here rather than with the harness.

    Its blind spots are real and stated in project-conventions: it sees tables,
    columns, types and regular indexes, and is blind to functions, triggers,
    partial indexes and CHECK constraints. Passing means the tables match, not
    that the migration is complete.
    """
    command.check(make_alembic_config(migrated_database))


def test_the_notice_backfill_reaches_rows_that_predate_it(
    disposable_database: str, make_alembic_config: ConfigFactory
) -> None:
    """A migration's backfill is the half no ordinary test can reach.

    Every other test creates a fresh offering, which takes the column *default* —
    so the `UPDATE` in `f1b6a92c7d4e` could be deleted entirely and the whole
    suite would stay green. A mutation proved exactly that. A fresh
    migrate-then-load cannot reach it either: migrations run before any data is
    loaded, so those rows also take the default.

    The backfill only matters for rows that **predate** the migration — the
    migrated offerings sitting at 120 in staging and production, which is the
    entire population this PR exists to correct. Reaching them needs a row
    created at the prior revision, so this test upgrades to it, writes one, and
    then upgrades the rest of the way.
    """
    config = make_alembic_config(disposable_database)
    command.upgrade(config, "c9d4e2a71f68")

    execute(
        disposable_database,
        """
        WITH u AS (
            INSERT INTO users (email, auth_id, first_name, primary_role, timezone)
            VALUES ('backfill@example.test', gen_random_uuid(), 'Probe', 'mentor', 'UTC')
            RETURNING id
        ), p AS (
            INSERT INTO mentor_profiles (user_id, headline) SELECT id, 'P' FROM u
            RETURNING user_id
        ), t AS (
            INSERT INTO session_types (mentor_user_id, name)
            SELECT user_id, 'Predates the migration' FROM p RETURNING id
        )
        INSERT INTO session_type_booking_configs
            (session_type_id, duration_minutes, min_notice_minutes)
        SELECT id, 45, 120 FROM t
        """,
    )
    assert (
        scalar(disposable_database, "SELECT min_notice_minutes FROM session_type_booking_configs")
        == 120
    )

    command.upgrade(config, "head")

    assert (
        scalar(disposable_database, "SELECT min_notice_minutes FROM session_type_booking_configs")
        == 1440
    ), (
        "the backfill did not reach a row that predates it; every migrated "
        "offering would keep two-hour notice while the default reads twenty-four"
    )


def test_the_topic_backfill_carries_every_classified_session_type(
    disposable_database: str, make_alembic_config: ConfigFactory
) -> None:
    """Session Types #9 moves a type's offering into `session_type_offerings`.

    Only a type created **before** the migration exercises the backfill; every
    fresh type is written by the new code. So this writes one at the prior
    revision — classified — and one unclassified, then upgrades over them: the
    first must arrive as a set of one, the second as nothing.
    """
    config = make_alembic_config(disposable_database)
    command.upgrade(config, "030c8bba5d6e")

    execute(
        disposable_database,
        """
        WITH u AS (
            INSERT INTO users (email, auth_id, first_name, primary_role, timezone)
            VALUES ('topics@example.test', gen_random_uuid(), 'Probe', 'mentor', 'UTC')
            RETURNING id
        ), p AS (
            INSERT INTO mentor_profiles (user_id, headline) SELECT id, 'P' FROM u
            RETURNING user_id
        )
        INSERT INTO session_types (mentor_user_id, name, service_offering_id)
        SELECT user_id, 'Classified',
               (SELECT id FROM service_offerings WHERE slug = 'test-preparation')
        FROM p
        UNION ALL
        SELECT user_id, 'Unclassified', NULL FROM p
        """,
    )

    command.upgrade(config, "head")

    assert (
        scalar(
            disposable_database,
            "SELECT count(*) FROM session_type_offerings o JOIN session_types t "
            "ON t.id = o.session_type_id AND t.service_offering_id = o.service_offering_id "
            "WHERE t.name = 'Classified'",
        )
        == 1
    ), "a classified type that predates the migration lost its offering"
    assert scalar(disposable_database, "SELECT count(*) FROM session_type_offerings") == 1, (
        "an unclassified type must not gain a row"
    )


def test_the_confirmation_seed_reads_the_offerings_before_clearing_them(
    disposable_database: str, make_alembic_config: ConfigFactory
) -> None:
    """**The one regression `b4e9c72a1d58` can cause, and it is invisible.**

    The migration seeds `mentor_profiles.requires_booking_confirmation` from the
    offerings and *then* clears them. Reversing those two statements, or seeding
    from the column default instead, leaves every mentor who required
    confirmation silently not requiring it — with the row count unchanged, every
    constraint satisfied, and every other test green, because every other test
    creates a fresh mentor who takes the default.

    So this writes an offering at `true` under the prior revision, where the
    mentor column does not exist yet and the offering is the only place the
    setting lives, and upgrades over it.

    The second assertion is the other half and fails on a different mistake: a
    migration that seeded correctly but left the offerings holding their values
    would turn every migrated offering into a permanent override, and the
    mentor's toggle would stop having any effect on what a reader resolves.
    """
    config = make_alembic_config(disposable_database)
    command.upgrade(config, "e7b4d29c3f16")

    execute(
        disposable_database,
        """
        WITH u AS (
            INSERT INTO users (email, auth_id, first_name, primary_role, timezone)
            VALUES ('confirm@example.test', gen_random_uuid(), 'Probe', 'mentor', 'UTC')
            RETURNING id
        ), p AS (
            INSERT INTO mentor_profiles (user_id, headline) SELECT id, 'P' FROM u
            RETURNING user_id
        ), t AS (
            INSERT INTO session_types (mentor_user_id, name)
            SELECT user_id, 'Predates the migration' FROM p RETURNING id
        )
        INSERT INTO session_type_booking_configs
            (session_type_id, duration_minutes, requires_booking_confirmation)
        SELECT id, 45, true FROM t
        """,
    )

    command.upgrade(config, "head")

    assert (
        scalar(disposable_database, "SELECT requires_booking_confirmation FROM mentor_profiles")
        is True
    ), (
        "the seed did not carry the offering's setting up to the mentor; every "
        "mentor who required confirmation would silently stop requiring it"
    )
    assert (
        scalar(
            disposable_database,
            "SELECT requires_booking_confirmation FROM session_type_booking_configs",
        )
        is None
    ), (
        "the offering kept its value instead of inheriting; it is now a "
        "permanent override and the mentor's toggle resolves to nothing"
    )


def test_the_conferencing_backfill_seeds_before_it_drops(
    disposable_database: str, make_alembic_config: ConfigFactory
) -> None:
    """**The named regression for `d9e2b74c1f36`, and it is invisible otherwise.**

    The migration seeds `mentor_conferencing_options` from `meeting_venue` and
    points each offering at its own row *before* dropping the column. Reversing
    those loses the only source silently: every row count still reconciles, and
    every migrated offering then resolves through the platform fallback — so a
    mentor on `daily` becomes Google Meet with nothing reporting it.

    Two mentors, because the two paths differ. `daily` is carried faithfully.
    `custom` **cannot be** — the symmetric `CHECK` requires a URL and the legacy
    schema has none — so that mentor is seeded `google_meet`, their offering's
    pointer stays null, and the quarantine is what makes the difference visible.

    `sessions.meeting_provider` is asserted untouched in the same test: it is a
    different column on a different table with a *wider* vocabulary, and the
    cheap mistake is a migration that tidies both.

    **Asserted at `d9e2b74c1f36`, then at head.** The quarantine's `google_meet`
    was right when the fallback was Meet. `a7c4e2d91f3b` removes imported Meet
    rows because the fallback is now `daily`, which keeps the mentor bookable with
    no option at all. So the old guarantee is checked at its own revision, and
    head checks that the same mentor resolves to the platform default.
    """
    config = make_alembic_config(disposable_database)
    command.upgrade(config, "c8f1a3e2b904")

    execute(
        disposable_database,
        """
        WITH u AS (
            INSERT INTO users (email, auth_id, first_name, primary_role, timezone)
            VALUES ('venue-daily@example.test', gen_random_uuid(), 'D', 'mentor', 'UTC'),
                   ('venue-custom@example.test', gen_random_uuid(), 'C', 'mentor', 'UTC')
            RETURNING id, email
        ), p AS (
            INSERT INTO mentor_profiles (user_id, headline) SELECT id, 'P' FROM u
            RETURNING user_id
        ), t AS (
            INSERT INTO session_types (mentor_user_id, name)
            SELECT user_id, 'Offering' FROM p RETURNING id, mentor_user_id
        )
        INSERT INTO session_type_booking_configs
            (session_type_id, duration_minutes, meeting_venue)
        SELECT t.id, 45,
               CASE WHEN u.email LIKE 'venue-daily%' THEN 'daily' ELSE 'custom' END
          FROM t JOIN u ON u.id = t.mentor_user_id
        """,
    )

    command.upgrade(config, "d9e2b74c1f36")

    # The faithful path: the option exists and the offering points at it.
    assert (
        scalar(
            disposable_database,
            "SELECT o.provider FROM session_types st "
            "  JOIN mentor_conferencing_options o "
            "    ON o.id = st.conferencing_option_id AND o.user_id = st.mentor_user_id "
            "  JOIN users u ON u.id = st.mentor_user_id "
            " WHERE u.email LIKE 'venue-daily%'",
        )
        == "daily"
    ), "the backfill did not carry `daily`; every migrated mentor resolves to the fallback"

    # The quarantined path: seeded google_meet, pointer left null.
    assert (
        scalar(
            disposable_database,
            "SELECT o.provider FROM mentor_conferencing_options o "
            "  JOIN users u ON u.id = o.user_id "
            " WHERE u.email LIKE 'venue-custom%'",
        )
        == "google_meet"
    ), "a mentor whose only venue was `custom` was left with no option and is unbookable"
    assert (
        scalar(
            disposable_database,
            "SELECT st.conferencing_option_id FROM session_types st "
            "  JOIN users u ON u.id = st.mentor_user_id "
            " WHERE u.email LIKE 'venue-custom%'",
        )
        is None
    ), "a custom offering was pointed at a substituted venue instead of inheriting it"

    assert scalar(disposable_database, "SELECT count(*) FROM mentor_conferencing_options") == 2, (
        "one option per mentor, and the quarantine must not create a second"
    )

    command.upgrade(config, "head")

    # At head the quarantined mentor holds no option and resolves the same way
    # `_resolved_venue` does: chosen, else default, else the platform default.
    resolved = (
        "SELECT coalesce(c.provider, d.provider, '{fallback}') FROM session_types st "
        "  JOIN users u ON u.id = st.mentor_user_id "
        "  LEFT JOIN mentor_conferencing_options c "
        "    ON c.id = st.conferencing_option_id AND c.user_id = st.mentor_user_id "
        "  LEFT JOIN mentor_conferencing_options d "
        "    ON d.user_id = st.mentor_user_id AND d.is_default "
        " WHERE u.email LIKE '{email}'"
    )
    fallback = PLATFORM_DEFAULT_PROVIDER.value
    assert fallback == "daily"
    assert (
        scalar(disposable_database, resolved.format(fallback=fallback, email="venue-custom%"))
        == "daily"
    ), "a mentor whose only venue was `custom` is not on the platform default"
    assert (
        scalar(disposable_database, resolved.format(fallback=fallback, email="venue-daily%"))
        == "daily"
    ), "a carried `daily` choice did not survive to head"


def test_the_primary_pointer_downgrade_restores_data_not_just_a_column(
    disposable_database: str, make_alembic_config: ConfigFactory
) -> None:
    """**A downgrade that restores an empty column is not a downgrade.**

    `c8f1a3e2b904` drops `primary_session_type_id` and
    `trg_refuse_retiring_a_primary_offering`. Recreating the column, the key, the
    function and the trigger restores the *mechanism* and leaves it inert: every
    pointer would be null, so the guard would refuse nothing and every reader
    through it would resolve to nothing. Both directions of `alembic` would report
    success and `test_upgrade_downgrade_upgrade_is_clean` would stay green,
    because it asserts the chain runs rather than what it leaves behind.

    So this creates a mentor with a live offering at head, downgrades one step,
    and asserts the pointer **points at that offering** — the re-seed, not the
    column.
    """
    config = make_alembic_config(disposable_database)
    command.upgrade(config, "head")

    execute(
        disposable_database,
        """
        WITH u AS (
            INSERT INTO users (email, auth_id, first_name, primary_role, timezone)
            VALUES ('reseed@example.test', gen_random_uuid(), 'Probe', 'mentor', 'UTC')
            RETURNING id
        ), p AS (
            INSERT INTO mentor_profiles (user_id, headline) SELECT id, 'P' FROM u
            RETURNING user_id
        )
        INSERT INTO session_types (mentor_user_id, name)
        SELECT user_id, 'Live offering' FROM p
        """,
    )

    command.downgrade(config, "b4e9c72a1d58")

    assert (
        scalar(
            disposable_database,
            "SELECT mp.primary_session_type_id = st.id "
            "  FROM mentor_profiles mp JOIN session_types st ON st.mentor_user_id = mp.user_id",
        )
        is True
    ), (
        "the downgrade restored the column without re-seeding it; the guard is "
        "installed and inert, and every read through the pointer resolves to null"
    )


def test_upgrade_downgrade_upgrade_is_clean(
    disposable_database: str, make_alembic_config: ConfigFactory
) -> None:
    """An untested downgrade is decoration, so this actually runs one.

    Extensions deliberately survive the downgrade; only the functions are
    dropped. Asserting that explicitly stops someone "fixing" the asymmetry
    without reading why it exists.

    **Enum types must NOT survive it**, and that is the assertion this test
    exists for now that M1 creates five of them. ``DROP TABLE`` removes a
    table's indexes, constraints and triggers but leaves an enum type standing —
    types are schema-level objects with their own lifetime, and autogenerate
    never emits the ``DROP TYPE``. The orphan is invisible until the *second*
    upgrade fails with ``type "primary_role" already exists``, which is why the
    re-upgrade below is not ceremony.
    """
    config = make_alembic_config(disposable_database)

    command.upgrade(config, "head")
    command.downgrade(config, "base")

    assert function_names(disposable_database) == [], (
        "functions outlived the chain; the next upgrade will fail on 'already exists'"
    )
    assert has_pgcrypto(disposable_database)
    assert enum_type_names(disposable_database) == [], (
        "enum types outlived their tables; the next upgrade will fail on 'type already exists'"
    )

    command.upgrade(config, "head")

    assert function_names(disposable_database) == sorted(FUNCTION_NAMES)
    assert enum_type_names(disposable_database) == sorted(ENUM_TYPE_NAMES)


def schema_identifiers(url: str) -> list[str]:
    """Every constraint, index and enum type name the built schema holds."""

    async def _run() -> list[str]:
        conn = await asyncpg.connect(url)
        try:
            rows = await conn.fetch(
                "SELECT c.conname AS name FROM pg_constraint c "
                "JOIN pg_namespace n ON n.oid = c.connamespace WHERE n.nspname = 'public' "
                "UNION SELECT indexname FROM pg_indexes WHERE schemaname = 'public' "
                "UNION SELECT t.typname FROM pg_type t "
                "JOIN pg_namespace tn ON tn.oid = t.typnamespace "
                "WHERE t.typtype = 'e' AND tn.nspname = 'public'"
            )
            return sorted(row["name"] for row in rows)
        finally:
            await conn.close()

    return asyncio.run(_run())


#: Names the database holds that are never *declared* by that name in source.
#:
#: All three are the same case, which is why they belong together: a name the
#: naming convention produced from a shorter declared one — ``email_is_lowercase``
#: becomes ``ck_users_email_is_lowercase`` — plus alembic's own
#: ``alembic_version_pkc``. That is what the convention is for, so these are
#: exceptions to state rather than to discover.
#:
#: ``ck_users_email_is_lowercase`` was missing, and the test passed anyway. It
#: appears in source in exactly two places, both **prose**: a comment in an
#: unrelated migration explaining a historical double-render. A substring match
#: over file text cannot tell a declaration from a sentence about one, so tidying
#: that comment would have turned this red — and told the reader a 27-character
#: name had been truncated past 63 bytes. Found in review, not by the test.
UNSOURCED_IDENTIFIERS = frozenset(
    {
        "alembic_version_pkc",
        "ck_admin_users_revoker_implies_revocation",
        "ck_users_email_is_lowercase",
    }
)

SOURCE_ROOTS = (Path("src"), Path("migrations"))


def test_every_schema_identifier_appears_verbatim_in_source(
    disposable_database: str, make_alembic_config: ConfigFactory
) -> None:
    """Catches a **silently truncated** identifier, from any source.

    PostgreSQL's limit is 63 bytes and SQLAlchemy does not reject a longer name —
    it truncates and appends a deterministic hash, with no warning and no
    ``NOTICE``. The database then holds an identifier that appears nowhere in the
    repository, and the first ``op.drop_constraint`` written against the declared
    name fails with *constraint does not exist* — handed the wrong name by the
    very file somebody opened to look it up.

    Nothing else in the gate can see it: **``alembic check`` compares foreign
    keys by column signature, never by name**, and no other check reads
    constraint names at all. A 65-character key shipped this way through six
    green CI checks and a thirteen-way mutation batch, and a reviewer querying
    ``pg_constraint`` found it.

    ``test_no_declared_identifier_exceeds_the_postgresql_limit`` closes the same
    hole at declaration time by walking ``Base.metadata``. This one is wider on
    purpose: a name written directly into a **migration** and into no model is
    invisible to that test, and both migrations in M2 hand-write names.
    """
    command.upgrade(make_alembic_config(disposable_database), "head")

    source = "\n".join(
        path.read_text(encoding="utf-8", errors="ignore")
        for root in SOURCE_ROOTS
        for path in root.rglob("*.py")
    )

    # A **quoted** occurrence, not a bare substring. Every identifier this test
    # is meant to protect is declared as a string literal — `Index("ix_…")`,
    # `name=op.f("fk_…")`, an enum label in `ENUM_TYPES` — so requiring the
    # quotes demands a declaration and rejects a passing mention.
    #
    # The looser version passed on a name that appears only inside a comment, and
    # would have gone red the day somebody edited that comment. A test that
    # depends on prose is a test that reports on the prose.
    missing = [
        name
        for name in schema_identifiers(disposable_database)
        if name not in UNSOURCED_IDENTIFIERS and f'"{name}"' not in source
    ]

    assert missing == [], (
        "these identifiers exist in the database but appear nowhere in src/ or "
        f"migrations/ — most likely silently truncated past 63 bytes: {missing}"
    )


#: A mentor with one offering, as the precedent above builds one; the caller
#: formats in the email, name, stage and label as SQL literals.
_MENTOR_WITH_OFFERING = """
    WITH u AS (
        INSERT INTO users (email, auth_id, first_name, primary_role, timezone)
        VALUES ('{email}', gen_random_uuid(), 'Probe', 'mentor', 'UTC')
        RETURNING id
    ), p AS (
        INSERT INTO mentor_profiles (user_id, headline) SELECT id, 'P' FROM u
        RETURNING user_id
    )
    INSERT INTO session_types (mentor_user_id, name, application_stage, custom_stage_label)
    SELECT user_id, '{name}', {stage}, {label} FROM p
"""


def test_the_stage_set_backfill_carries_every_staged_type(
    disposable_database: str, make_alembic_config: ConfigFactory
) -> None:
    """`e0d7461f13ce` backfills one row per type with a stage, at position 0,
    and none for a type aimed at any stage (#215)."""
    config = make_alembic_config(disposable_database)
    command.upgrade(config, "7b3e91c4a2d6")
    execute(
        disposable_database,
        _MENTOR_WITH_OFFERING.format(
            email="staged@example.test", name="Staged", stage="'revisions'", label="NULL"
        ),
    )
    execute(
        disposable_database,
        _MENTOR_WITH_OFFERING.format(
            email="any@example.test", name="Any", stage="NULL", label="NULL"
        ),
    )

    command.upgrade(config, "e0d7461f13ce")

    assert (
        scalar(
            disposable_database,
            "SELECT string_agg(t.name || ':' || s.stage || ':' || s.position, ',') "
            "FROM session_type_stages s JOIN session_types t ON t.id = s.session_type_id",
        )
        == "Staged:revisions:0"
    )


def test_the_stage_set_downgrade_keeps_the_mentors_label(
    disposable_database: str, make_alembic_config: ConfigFactory
) -> None:
    """**`[drafting_stage, other]` with a label cannot survive as one stage whole.**
    The symmetric `CHECK` the downgrade restores needs the label and `other`
    together, so the single stage becomes `other` and the mentor's wording is
    kept — the documented choice over keeping `drafting_stage` and dropping the
    label, which would lose the only thing the mentor typed."""
    config = make_alembic_config(disposable_database)
    command.upgrade(config, "e0d7461f13ce")
    execute(
        disposable_database,
        _MENTOR_WITH_OFFERING.format(
            email="set@example.test", name="Set", stage="'drafting_stage'", label="'Gap year'"
        ),
    )
    execute(
        disposable_database,
        "INSERT INTO session_type_stages (session_type_id, stage, position) "
        "SELECT id, 'drafting_stage', 0 FROM session_types WHERE name = 'Set' "
        "UNION ALL SELECT id, 'other', 1 FROM session_types WHERE name = 'Set'",
    )

    command.downgrade(config, "7b3e91c4a2d6")

    assert (
        scalar(
            disposable_database,
            "SELECT application_stage || ':' || custom_stage_label FROM session_types "
            "WHERE name = 'Set'",
        )
        == "other:Gap year"
    )


def test_the_inherit_downgrade_writes_the_resolved_values(
    disposable_database: str, make_alembic_config: ConfigFactory
) -> None:
    """`228315723d63`'s downgrade restores `NOT NULL`, so an inheriting offering
    must first be given **the value it was resolving to** — its mentor's default,
    else the platform's — not a column default nobody chose (#216)."""
    config = make_alembic_config(disposable_database)
    command.upgrade(config, "228315723d63")
    execute(
        disposable_database,
        _MENTOR_WITH_OFFERING.format(
            email="inherit@example.test", name="Inherits", stage="NULL", label="NULL"
        ),
    )
    execute(
        disposable_database,
        _MENTOR_WITH_OFFERING.format(
            email="inherit-notice@example.test", name="Inherits notice", stage="NULL", label="NULL"
        ),
    )
    # Each column once from the mentor's default and once from the platform's:
    # the first mentor sets only a length, the second only a notice.
    execute(
        disposable_database,
        "UPDATE mentor_profiles SET default_duration_minutes = 30 "
        "WHERE user_id = (SELECT id FROM users WHERE email = 'inherit@example.test'); "
        "UPDATE mentor_profiles SET default_min_notice_minutes = 2880 "
        "WHERE user_id = (SELECT id FROM users WHERE email = 'inherit-notice@example.test'); "
        "INSERT INTO session_type_booking_configs "
        "(session_type_id, duration_minutes, min_notice_minutes) "
        "SELECT id, NULL, NULL FROM session_types",
    )

    command.downgrade(config, "e0d7461f13ce")

    assert (
        scalar(
            disposable_database,
            "SELECT string_agg(t.name || '=' || c.duration_minutes || ':' || "
            "c.min_notice_minutes, ',' ORDER BY t.name) "
            "FROM session_type_booking_configs c JOIN session_types t ON t.id = c.session_type_id",
        )
        == "Inherits=30:1440,Inherits notice=60:2880"
    )
    assert (
        scalar(
            disposable_database,
            "SELECT bool_and(attnotnull) FROM pg_attribute "
            "WHERE attrelid = 'session_type_booking_configs'::regclass "
            "AND attname IN ('duration_minutes', 'min_notice_minutes')",
        )
        is True
    )


def test_featured_and_scheduled_deletion_arrive_as_defaults(
    disposable_database: str, make_alembic_config: ConfigFactory
) -> None:
    """`f3a91d2c7b45` adds both columns under existing rows as un-featured and
    unscheduled — what every offering was — and the constraints validate over
    them (#217, #218)."""
    config = make_alembic_config(disposable_database)
    command.upgrade(config, "228315723d63")
    execute(
        disposable_database,
        _MENTOR_WITH_OFFERING.format(
            email="round4-up@example.test", name="Existing", stage="NULL", label="NULL"
        ),
    )

    command.upgrade(config, "f3a91d2c7b45")

    assert (
        scalar(
            disposable_database,
            "SELECT is_featured::text || ':' || (deletion_scheduled_at IS NULL)::text "
            "FROM session_types WHERE name = 'Existing'",
        )
        == "false:true"
    )
    assert (
        scalar(
            disposable_database,
            "SELECT bool_and(convalidated) FROM pg_constraint WHERE conname IN "
            "('ck_session_types_featured_is_active', "
            "'ck_session_types_scheduled_deletion_is_hidden')",
        )
        is True
    )


def test_the_round_four_downgrade_keeps_a_scheduled_offering_hidden(
    disposable_database: str, make_alembic_config: ConfigFactory
) -> None:
    """Down, a featured offering keeps its row and loses only its place first,
    and a scheduled one stays **hidden and undeleted** — the old code's `409`
    then refuses its `DELETE` again, which is where it was."""
    config = make_alembic_config(disposable_database)
    command.upgrade(config, "f3a91d2c7b45")
    execute(
        disposable_database,
        _MENTOR_WITH_OFFERING.format(
            email="round4-feat@example.test", name="Featured", stage="NULL", label="NULL"
        ),
    )
    execute(
        disposable_database,
        _MENTOR_WITH_OFFERING.format(
            email="round4-sched@example.test", name="Scheduled", stage="NULL", label="NULL"
        ),
    )
    execute(
        disposable_database,
        "UPDATE session_types SET is_featured = true WHERE name = 'Featured'; "
        "UPDATE session_types SET is_active = false, deletion_scheduled_at = now() "
        "WHERE name = 'Scheduled'",
    )

    command.downgrade(config, "228315723d63")

    assert (
        scalar(
            disposable_database,
            "SELECT string_agg(name || '=' || is_active::text || ':' || "
            "(deleted_at IS NULL)::text, ',' ORDER BY name) FROM session_types",
        )
        == "Featured=true:true,Scheduled=false:true"
    )
    assert (
        scalar(
            disposable_database,
            "SELECT count(*) FROM information_schema.columns WHERE table_name = "
            "'session_types' AND column_name IN ('is_featured', 'deletion_scheduled_at')",
        )
        == 0
    )


_OPTION = """
    INSERT INTO mentor_conferencing_options (user_id, provider, is_default)
    SELECT id, '{provider}', {default} FROM users WHERE email = '{email}'
"""

_POINT = """
    UPDATE session_types st SET conferencing_option_id = o.id
      FROM mentor_conferencing_options o, users u
     WHERE u.email = '{email}' AND st.mentor_user_id = u.id
       AND o.user_id = u.id AND o.provider = '{provider}'
"""

_VENUES = """
    SELECT string_agg(
        u.email || '=' || coalesce((
            SELECT string_agg(
                o.provider::text || (CASE WHEN o.is_default THEN '*' ELSE '' END),
                '+' ORDER BY o.provider::text)
              FROM mentor_conferencing_options o WHERE o.user_id = u.id), '-')
        || '>' || coalesce((
            SELECT o.provider::text FROM session_types st
              JOIN mentor_conferencing_options o ON o.id = st.conferencing_option_id
             WHERE st.mentor_user_id = u.id), 'none'),
        ',' ORDER BY u.email)
      FROM users u WHERE u.email LIKE 'venue-%'
"""


def _venue_probes(url: str) -> None:
    """A never chose (an imported `google_meet` default). B chose daily. C has a
    daily default plus an imported `google_meet` its offering points at."""
    for email in ("venue-a@example.test", "venue-b@example.test", "venue-c@example.test"):
        execute(
            url, _MENTOR_WITH_OFFERING.format(email=email, name=email, stage="NULL", label="NULL")
        )
    for email, provider, default in (
        ("venue-a@example.test", "google_meet", "true"),
        ("venue-b@example.test", "daily", "true"),
        ("venue-c@example.test", "daily", "true"),
        ("venue-c@example.test", "google_meet", "false"),
    ):
        execute(url, _OPTION.format(email=email, provider=provider, default=default))
    for email, provider in (
        ("venue-a@example.test", "google_meet"),
        ("venue-b@example.test", "daily"),
        ("venue-c@example.test", "google_meet"),
    ):
        execute(url, _POINT.format(email=email, provider=provider))


def test_imported_meet_options_go_so_nobody_is_held_to_a_choice_they_never_made(
    disposable_database: str, make_alembic_config: ConfigFactory
) -> None:
    """`a7c4e2d91f3b`: before `/me/conferencing` (#224) nothing let a mentor
    choose Meet, so every `google_meet` option was imported from a blank or an
    unrepresentable legacy venue. They go, with the pointers to them; a genuine
    `daily` choice stays."""
    config = make_alembic_config(disposable_database)
    command.upgrade(config, "f3a91d2c7b45")
    _venue_probes(disposable_database)
    assert scalar(disposable_database, _VENUES) == (
        "venue-a@example.test=google_meet*>google_meet,"
        "venue-b@example.test=daily*>daily,"
        "venue-c@example.test=daily*+google_meet>google_meet"
    )

    command.upgrade(config, "a7c4e2d91f3b")

    assert scalar(disposable_database, _VENUES) == (
        "venue-a@example.test=->none,"
        "venue-b@example.test=daily*>daily,"
        "venue-c@example.test=daily*>none"
    )


def test_a_meet_the_mentor_chose_survives_a_downgrade_and_upgrade(
    disposable_database: str, make_alembic_config: ConfigFactory
) -> None:
    """Provenance, not provider, decides what the cleanup removes: `source`
    records who wrote the row, so a Meet set through `/me/conferencing` is kept
    when `a7c4e2d91f3b` runs again after a downgrade, and an imported one goes."""
    config = make_alembic_config(disposable_database)
    command.upgrade(config, "a7c4e2d91f3b")
    for email in ("venue-chose@example.test", "venue-import@example.test"):
        execute(
            disposable_database,
            _MENTOR_WITH_OFFERING.format(email=email, name=email, stage="NULL", label="NULL"),
        )
    execute(
        disposable_database,
        "INSERT INTO mentor_conferencing_options (user_id, provider, is_default, source) "
        "SELECT id, 'google_meet', true, 'mentor' FROM users "
        "WHERE email = 'venue-chose@example.test'; "
        "INSERT INTO mentor_conferencing_options (user_id, provider, is_default) "
        "SELECT id, 'google_meet', true FROM users WHERE email = 'venue-import@example.test'",
    )

    command.downgrade(config, "-1")
    command.upgrade(config, "a7c4e2d91f3b")

    assert (
        scalar(
            disposable_database,
            "SELECT string_agg(u.email || '=' || o.source, ',' ORDER BY u.email) "
            "FROM mentor_conferencing_options o JOIN users u ON u.id = o.user_id "
            "WHERE u.email LIKE 'venue-%'",
        )
        == "venue-chose@example.test=mentor"
    )


def test_the_imported_meet_downgrade_restores_the_old_load_rule(
    disposable_database: str, make_alembic_config: ConfigFactory
) -> None:
    """Down, a mentor left with no default gets the `google_meet` default the old
    load gave them, and their offering points at it again. A mentor who kept a
    default is left alone: which imported option the old seeding made default is
    not recoverable, and their offering follows that default."""
    config = make_alembic_config(disposable_database)
    command.upgrade(config, "f3a91d2c7b45")
    _venue_probes(disposable_database)
    command.upgrade(config, "a7c4e2d91f3b")

    command.downgrade(config, "f3a91d2c7b45")

    assert scalar(disposable_database, _VENUES) == (
        "venue-a@example.test=google_meet*>google_meet,"
        "venue-b@example.test=daily*>daily,"
        "venue-c@example.test=daily*>none"
    )
