"""The migration chain itself.

Every test here runs against a database created for it and dropped afterwards,
and every one is synchronous: ``migrations/env.py`` calls ``asyncio.run``, which
raises ``RuntimeError`` if a loop is already running.
"""

import asyncio
from collections.abc import Callable
from pathlib import Path
from typing import Any

import asyncpg
import pytest
from alembic import command
from alembic.config import Config

pytestmark = pytest.mark.db

#: Every function the chain creates, at head — the exact set, not a count.
#:
#: This is the **only** guard on a function's name.
#: `test_every_schema_identifier_appears_verbatim_in_source` collects constraint
#: names, index names and enum type names; functions are in none of those, so
#: nothing else in the gate notices one renamed, dropped or added.
#:
#: `apply_mentor_status` was absent from this tuple for two phases — M2 created
#: it and the assertion was a count over a hard-coded list, which could not see
#: it. `timerange` and `timemultirange` are generated by M3's `CREATE TYPE ... AS
#: RANGE` rather than written out; they are ours, and they are dropped with the
#: type. `session_window` joins in M4 (`d7c31f8a2b45`).
#:
#: `refuse_retiring_a_primary_offering` joined in `d5a83b17c9e4` and **left in
#: `c8f1a3e2b904`**, with `mentor_profiles.primary_session_type_id`. It was the
#: only **business-rule** function here — every remaining entry is
#: infrastructure — and it existed because `ON DELETE RESTRICT` cannot see a
#: retirement that happens as `deleted_at` or `is_active = false`, both UPDATEs.
#: With nothing pointing at a session type there is nothing for it to protect.
#: `tests/integration/test_offering_retirement.py` asserts its absence directly,
#: because this tuple would also pass against a trigger left in place over a
#: dropped function.
#:
#: This tuple catching a *new* one is the test doing its job: a schema-level
#: object added without a downgrade would survive `downgrade base` and break the
#: next upgrade on "already exists", which is exactly what the assertion above
#: the re-upgrade is for.
FUNCTION_NAMES = (
    "apply_mentor_status",
    "session_window",
    "set_updated_at",
    "timemultirange",
    "timerange",
    "uuid_generate_v7",
)

# Extensions the chain is expected to install, at head.
#
# `citext` is deliberately absent: M1 created it for `users.email` and
# `e25541374c03` dropped it again when normalisation moved to the boundary. The
# chain still creates and drops it in between, which is why this asserts the
# state at head rather than every extension the chain has ever touched.
# `pg_trgm` is the first extension whose *operators* the schema depends on:
# `pgcrypto` was declared for tidiness but `gen_random_uuid()` has been core
# since PostgreSQL 13, so a missing pgcrypto would never have surfaced. A missing
# pg_trgm fails loudly at `CREATE INDEX ... USING gin (name gin_trgm_ops)`.
#
# `btree_gist` joins them in M3 and is load-bearing in the same way: uuid has no
# GiST operator class without it, so `ix_availability_exceptions_range` cannot be
# built at all. It is the one extension the chain creates with `IF NOT EXISTS`,
# because Supabase already has it installed while the local and CI containers do
# not — and unlike the others it is never dropped on downgrade.
EXTENSION_NAMES = ("btree_gist", "pg_trgm", "pgcrypto")

# The exact set of tables at head, in the order `table_names` returns them.
#
# Asserting the exact list rather than a subset is what catches the reverse
# mistake: a table dropped, renamed, or never created because a migration was
# written but not added to the chain. It has to be updated in the same change
# that adds a table, which is the point — the same discipline as EXPECTED_MODELS
# in tests/unit/test_models.py.
EXPECTED_TABLES = [
    # M0 — reference data
    "countries",
    "languages",
    # M1 — identity
    "admin_users",
    "auth_identities",
    "legal_documents",
    "user_languages",
    "user_legal_consents",
    "user_onboarding",
    "user_profiles",
    "users",
    # M2 — the four lookups the profile tables reference
    "degree_levels",
    "institutions",
    "scholarship_programs",
    "service_offerings",
    # M2 — the profile tables themselves. `user_scholarship_experience` is
    # deliberately absent: no option set, no values, nothing to write it.
    "education_entries",
    "mentee_goal_countries",
    "mentee_goal_needs",
    "mentee_goals",
    "mentor_conferencing_options",
    "mentor_profiles",
    "mentor_service_offerings",
    "mentor_status_events",
    "user_awards",
    # M3 — availability. `calendar_connections` is deliberately absent: nothing
    # in M3 reads or writes it, and settled decision #21 ships it with the phase
    # that first needs it. See the M3 migration's docstring.
    "availability_exceptions",
    "availability_rules",
    # M4 — per-offering windows, which replace general availability for the
    # offering that has them. Listed with M4 rather than M3 because they are
    # a property of an offering.
    "session_type_scheduling_windows",
    # M4 — sessions. The four intake tables were deferred out of this phase and
    # have since landed, listed below. `session_notes` is still absent, for the
    # reason that deferred all five: no legacy source, no read surface, and
    # settled decision #21 ships a table with the phase that first needs it.
    # `calendar_connections` is still absent for the reason M3 recorded, now
    # joined by a second: the calendar integration goes direct to the Google API
    # rather than through Composio, so the columns encoding a Composio reference
    # are the wrong shape. See the M4 migration's docstring.
    "session_events",
    "session_participants",
    "session_type_booking_configs",
    "session_types",
    "sessions",
    # M4 — the intake stack, deferred out of `04_sessions.sql` when M4 shipped
    # and landing whole. `session_type_question_options` has no writer yet; see
    # its model for why shipping it early is now cheap.
    "intake_answers",
    "intake_submissions",
    "session_type_question_options",
    "session_type_questions",
]

# **No enum types at head, and that is settled decision #100 completed.**
#
# This tuple used to name every type the chain created, because a type outlives
# the table that used it: `DROP TABLE` does not remove one, so a downgrade that
# forgets leaves an orphan and the next upgrade fails on "already exists". Eight
# migrations converted all seventeen to `text` + `CHECK`, ending with
# `session_status` in `d3a6f81b52c7`.
#
# Empty is an assertion, not an absence of one: `enum_type_names(db) == []` fails
# the moment a migration creates a type. That is the regression to guard — the
# deferred `calendar_connections` and `search_impressions_suppressed` tables both
# declare enums in the canonical DDL, and building either verbatim would
# reintroduce one while every other gate stayed green.
ENUM_TYPE_NAMES: tuple[str, ...] = ()

ConfigFactory = Callable[[str], Config]


def scalar(url: str, sql: str) -> Any:
    async def _run() -> Any:
        conn = await asyncpg.connect(url)
        try:
            return await conn.fetchval(sql)
        finally:
            await conn.close()

    return asyncio.run(_run())


def execute(url: str, sql: str) -> None:
    """Mirrors `scalar`, for statements that return nothing."""

    async def _run() -> None:
        conn = await asyncpg.connect(url)
        try:
            await conn.execute(sql)
        finally:
            await conn.close()

    asyncio.run(_run())


def function_names(url: str) -> list[str]:
    """Every function **we** created, asked of the database rather than named.

    This was a count over a hard-coded name list, and that shape cannot fail in
    the direction that matters. Deriving the SQL from ``FUNCTION_NAMES`` made it
    strictly worse — the query then counted exactly the functions it named, so
    ``count == len(FUNCTION_NAMES)`` became a tautology. `session_window` was
    added, the tuple was not updated, and the assertion **passed**.

    Asking the schema instead caught something the count had hidden for two
    phases: ``apply_mentor_status`` — the function behind
    ``trg_apply_mentor_status``, which projects mentor status events onto their
    columns — had never been registered at all.

    Extension members are excluded through ``pg_depend``; `btree_gist`,
    `pg_trgm` and `pgcrypto` install into `public` and their functions are not
    ours. ``timerange`` and ``timemultirange`` *are* ours, generated by M3's
    ``CREATE TYPE ... AS RANGE`` rather than written by hand — distinct names, so
    the several arities of each collapse to one entry.
    """

    async def _run() -> list[str]:
        conn = await asyncpg.connect(url)
        try:
            rows = await conn.fetch(
                "SELECT DISTINCT p.proname FROM pg_proc p "
                "JOIN pg_namespace n ON n.oid = p.pronamespace "
                "WHERE n.nspname = 'public' AND NOT EXISTS ("
                "  SELECT 1 FROM pg_depend d WHERE d.objid = p.oid AND d.deptype = 'e') "
                "ORDER BY 1"
            )
            return [row["proname"] for row in rows]
        finally:
            await conn.close()

    return asyncio.run(_run())


def has_pgcrypto(url: str) -> bool:
    return scalar(url, "SELECT 1 FROM pg_extension WHERE extname = 'pgcrypto'") == 1


def extension_names(url: str) -> list[str]:
    """The extensions this project installs, by name.

    Returns names rather than a count, and filters in Python rather than in an
    interpolated ``IN`` list: a count tells you something is missing, a name
    tells you which. The query itself takes no input, so there is no string
    building to get wrong.
    """

    async def _run() -> list[str]:
        conn = await asyncpg.connect(url)
        try:
            rows = await conn.fetch("SELECT extname FROM pg_extension ORDER BY extname")
            return [row["extname"] for row in rows if row["extname"] in EXTENSION_NAMES]
        finally:
            await conn.close()

    return asyncio.run(_run())


def enum_type_names(url: str) -> list[str]:
    """Enum types in the public schema, whether or not any table still uses one.

    Deliberately not scoped to types a column references — an orphaned type is
    exactly the failure being watched for, and scoping the query that way would
    make it invisible.
    """

    async def _run() -> list[str]:
        conn = await asyncpg.connect(url)
        try:
            rows = await conn.fetch(
                "SELECT t.typname FROM pg_type t "
                "JOIN pg_namespace n ON n.oid = t.typnamespace "
                "WHERE t.typtype = 'e' AND n.nspname = 'public' ORDER BY t.typname"
            )
            return [row["typname"] for row in rows]
        finally:
            await conn.close()

    return asyncio.run(_run())


def table_names(url: str) -> list[str]:
    async def _run() -> list[str]:
        conn = await asyncpg.connect(url)
        try:
            rows = await conn.fetch(
                "SELECT tablename FROM pg_tables "
                "WHERE schemaname = 'public' AND tablename <> 'alembic_version' "
                "ORDER BY tablename"
            )
            return [row["tablename"] for row in rows]
        finally:
            await conn.close()

    return asyncio.run(_run())


def test_chain_applies_to_an_empty_database(
    disposable_database: str, make_alembic_config: ConfigFactory
) -> None:
    """From empty, not from wherever the developer's database happens to be.

    A chain that only runs from the current revision is broken for every new
    environment, and nothing reveals that until someone tries to provision one.
    """
    command.upgrade(make_alembic_config(disposable_database), "head")

    assert has_pgcrypto(disposable_database)
    assert extension_names(disposable_database) == sorted(EXTENSION_NAMES)
    assert function_names(disposable_database) == sorted(FUNCTION_NAMES)
    assert sorted(table_names(disposable_database)) == sorted(EXPECTED_TABLES)
    assert enum_type_names(disposable_database) == sorted(ENUM_TYPE_NAMES)


def test_models_and_the_chain_agree(
    migrated_database: str, make_alembic_config: ConfigFactory
) -> None:
    """``alembic check`` — the drift detector that only exists once models do.

    It compares the models against the schema the chain actually produced, and
    raises ``AutogenerateDiffsDetected`` when they disagree. Before PR 2 this
    passed trivially: with no models the metadata was empty, so there was nothing
    to differ. A check that cannot fail is not a check, which is why it arrives
    here rather than with the harness.

    Its blind spots are real and stated in project-conventions: it sees tables,
    columns, types and regular indexes, and is blind to functions, triggers,
    partial indexes and CHECK constraints. Passing means the tables match, not
    that the migration is complete.
    """
    command.check(make_alembic_config(migrated_database))


def test_the_notice_backfill_reaches_rows_that_predate_it(
    disposable_database: str, make_alembic_config: ConfigFactory
) -> None:
    """A migration's backfill is the half no ordinary test can reach.

    Every other test creates a fresh offering, which takes the column *default* —
    so the `UPDATE` in `f1b6a92c7d4e` could be deleted entirely and the whole
    suite would stay green. A mutation proved exactly that. A fresh
    migrate-then-load cannot reach it either: migrations run before any data is
    loaded, so those rows also take the default.

    The backfill only matters for rows that **predate** the migration — the
    migrated offerings sitting at 120 in staging and production, which is the
    entire population this PR exists to correct. Reaching them needs a row
    created at the prior revision, so this test upgrades to it, writes one, and
    then upgrades the rest of the way.
    """
    config = make_alembic_config(disposable_database)
    command.upgrade(config, "c9d4e2a71f68")

    execute(
        disposable_database,
        """
        WITH u AS (
            INSERT INTO users (email, auth_id, first_name, primary_role, timezone)
            VALUES ('backfill@example.test', gen_random_uuid(), 'Probe', 'mentor', 'UTC')
            RETURNING id
        ), p AS (
            INSERT INTO mentor_profiles (user_id, headline) SELECT id, 'P' FROM u
            RETURNING user_id
        ), t AS (
            INSERT INTO session_types (mentor_user_id, name)
            SELECT user_id, 'Predates the migration' FROM p RETURNING id
        )
        INSERT INTO session_type_booking_configs
            (session_type_id, duration_minutes, min_notice_minutes)
        SELECT id, 45, 120 FROM t
        """,
    )
    assert (
        scalar(disposable_database, "SELECT min_notice_minutes FROM session_type_booking_configs")
        == 120
    )

    command.upgrade(config, "head")

    assert (
        scalar(disposable_database, "SELECT min_notice_minutes FROM session_type_booking_configs")
        == 1440
    ), (
        "the backfill did not reach a row that predates it; every migrated "
        "offering would keep two-hour notice while the default reads twenty-four"
    )


def test_the_confirmation_seed_reads_the_offerings_before_clearing_them(
    disposable_database: str, make_alembic_config: ConfigFactory
) -> None:
    """**The one regression `b4e9c72a1d58` can cause, and it is invisible.**

    The migration seeds `mentor_profiles.requires_booking_confirmation` from the
    offerings and *then* clears them. Reversing those two statements, or seeding
    from the column default instead, leaves every mentor who required
    confirmation silently not requiring it — with the row count unchanged, every
    constraint satisfied, and every other test green, because every other test
    creates a fresh mentor who takes the default.

    So this writes an offering at `true` under the prior revision, where the
    mentor column does not exist yet and the offering is the only place the
    setting lives, and upgrades over it.

    The second assertion is the other half and fails on a different mistake: a
    migration that seeded correctly but left the offerings holding their values
    would turn every migrated offering into a permanent override, and the
    mentor's toggle would stop having any effect on what a reader resolves.
    """
    config = make_alembic_config(disposable_database)
    command.upgrade(config, "e7b4d29c3f16")

    execute(
        disposable_database,
        """
        WITH u AS (
            INSERT INTO users (email, auth_id, first_name, primary_role, timezone)
            VALUES ('confirm@example.test', gen_random_uuid(), 'Probe', 'mentor', 'UTC')
            RETURNING id
        ), p AS (
            INSERT INTO mentor_profiles (user_id, headline) SELECT id, 'P' FROM u
            RETURNING user_id
        ), t AS (
            INSERT INTO session_types (mentor_user_id, name)
            SELECT user_id, 'Predates the migration' FROM p RETURNING id
        )
        INSERT INTO session_type_booking_configs
            (session_type_id, duration_minutes, requires_booking_confirmation)
        SELECT id, 45, true FROM t
        """,
    )

    command.upgrade(config, "head")

    assert (
        scalar(disposable_database, "SELECT requires_booking_confirmation FROM mentor_profiles")
        is True
    ), (
        "the seed did not carry the offering's setting up to the mentor; every "
        "mentor who required confirmation would silently stop requiring it"
    )
    assert (
        scalar(
            disposable_database,
            "SELECT requires_booking_confirmation FROM session_type_booking_configs",
        )
        is None
    ), (
        "the offering kept its value instead of inheriting; it is now a "
        "permanent override and the mentor's toggle resolves to nothing"
    )


def test_the_conferencing_backfill_seeds_before_it_drops(
    disposable_database: str, make_alembic_config: ConfigFactory
) -> None:
    """**The named regression for `d9e2b74c1f36`, and it is invisible otherwise.**

    The migration seeds `mentor_conferencing_options` from `meeting_venue` and
    points each offering at its own row *before* dropping the column. Reversing
    those loses the only source silently: every row count still reconciles, and
    every migrated offering then resolves through the platform fallback — so a
    mentor on `daily` becomes Google Meet with nothing reporting it.

    Two mentors, because the two paths differ. `daily` is carried faithfully.
    `custom` **cannot be** — the symmetric `CHECK` requires a URL and the legacy
    schema has none — so that mentor is seeded `google_meet`, their offering's
    pointer stays null, and the quarantine is what makes the difference visible.

    `sessions.meeting_provider` is asserted untouched in the same test: it is a
    different column on a different table with a *wider* vocabulary, and the
    cheap mistake is a migration that tidies both.
    """
    config = make_alembic_config(disposable_database)
    command.upgrade(config, "c8f1a3e2b904")

    execute(
        disposable_database,
        """
        WITH u AS (
            INSERT INTO users (email, auth_id, first_name, primary_role, timezone)
            VALUES ('venue-daily@example.test', gen_random_uuid(), 'D', 'mentor', 'UTC'),
                   ('venue-custom@example.test', gen_random_uuid(), 'C', 'mentor', 'UTC')
            RETURNING id, email
        ), p AS (
            INSERT INTO mentor_profiles (user_id, headline) SELECT id, 'P' FROM u
            RETURNING user_id
        ), t AS (
            INSERT INTO session_types (mentor_user_id, name)
            SELECT user_id, 'Offering' FROM p RETURNING id, mentor_user_id
        )
        INSERT INTO session_type_booking_configs
            (session_type_id, duration_minutes, meeting_venue)
        SELECT t.id, 45,
               CASE WHEN u.email LIKE 'venue-daily%' THEN 'daily' ELSE 'custom' END
          FROM t JOIN u ON u.id = t.mentor_user_id
        """,
    )

    command.upgrade(config, "head")

    # The faithful path: the option exists and the offering points at it.
    assert (
        scalar(
            disposable_database,
            "SELECT o.provider FROM session_types st "
            "  JOIN mentor_conferencing_options o "
            "    ON o.id = st.conferencing_option_id AND o.user_id = st.mentor_user_id "
            "  JOIN users u ON u.id = st.mentor_user_id "
            " WHERE u.email LIKE 'venue-daily%'",
        )
        == "daily"
    ), "the backfill did not carry `daily`; every migrated mentor resolves to the fallback"

    # The quarantined path: seeded google_meet, pointer left null.
    assert (
        scalar(
            disposable_database,
            "SELECT o.provider FROM mentor_conferencing_options o "
            "  JOIN users u ON u.id = o.user_id "
            " WHERE u.email LIKE 'venue-custom%'",
        )
        == "google_meet"
    ), "a mentor whose only venue was `custom` was left with no option and is unbookable"
    assert (
        scalar(
            disposable_database,
            "SELECT st.conferencing_option_id FROM session_types st "
            "  JOIN users u ON u.id = st.mentor_user_id "
            " WHERE u.email LIKE 'venue-custom%'",
        )
        is None
    ), "a custom offering was pointed at a substituted venue instead of inheriting it"

    assert scalar(disposable_database, "SELECT count(*) FROM mentor_conferencing_options") == 2, (
        "one option per mentor, and the quarantine must not create a second"
    )


def test_the_primary_pointer_downgrade_restores_data_not_just_a_column(
    disposable_database: str, make_alembic_config: ConfigFactory
) -> None:
    """**A downgrade that restores an empty column is not a downgrade.**

    `c8f1a3e2b904` drops `primary_session_type_id` and
    `trg_refuse_retiring_a_primary_offering`. Recreating the column, the key, the
    function and the trigger restores the *mechanism* and leaves it inert: every
    pointer would be null, so the guard would refuse nothing and every reader
    through it would resolve to nothing. Both directions of `alembic` would report
    success and `test_upgrade_downgrade_upgrade_is_clean` would stay green,
    because it asserts the chain runs rather than what it leaves behind.

    So this creates a mentor with a live offering at head, downgrades one step,
    and asserts the pointer **points at that offering** — the re-seed, not the
    column.
    """
    config = make_alembic_config(disposable_database)
    command.upgrade(config, "head")

    execute(
        disposable_database,
        """
        WITH u AS (
            INSERT INTO users (email, auth_id, first_name, primary_role, timezone)
            VALUES ('reseed@example.test', gen_random_uuid(), 'Probe', 'mentor', 'UTC')
            RETURNING id
        ), p AS (
            INSERT INTO mentor_profiles (user_id, headline) SELECT id, 'P' FROM u
            RETURNING user_id
        )
        INSERT INTO session_types (mentor_user_id, name)
        SELECT user_id, 'Live offering' FROM p
        """,
    )

    command.downgrade(config, "b4e9c72a1d58")

    assert (
        scalar(
            disposable_database,
            "SELECT mp.primary_session_type_id = st.id "
            "  FROM mentor_profiles mp JOIN session_types st ON st.mentor_user_id = mp.user_id",
        )
        is True
    ), (
        "the downgrade restored the column without re-seeding it; the guard is "
        "installed and inert, and every read through the pointer resolves to null"
    )


def test_upgrade_downgrade_upgrade_is_clean(
    disposable_database: str, make_alembic_config: ConfigFactory
) -> None:
    """An untested downgrade is decoration, so this actually runs one.

    Extensions deliberately survive the downgrade; only the functions are
    dropped. Asserting that explicitly stops someone "fixing" the asymmetry
    without reading why it exists.

    **Enum types must NOT survive it**, and that is the assertion this test
    exists for now that M1 creates five of them. ``DROP TABLE`` removes a
    table's indexes, constraints and triggers but leaves an enum type standing —
    types are schema-level objects with their own lifetime, and autogenerate
    never emits the ``DROP TYPE``. The orphan is invisible until the *second*
    upgrade fails with ``type "primary_role" already exists``, which is why the
    re-upgrade below is not ceremony.
    """
    config = make_alembic_config(disposable_database)

    command.upgrade(config, "head")
    command.downgrade(config, "base")

    assert function_names(disposable_database) == [], (
        "functions outlived the chain; the next upgrade will fail on 'already exists'"
    )
    assert has_pgcrypto(disposable_database)
    assert enum_type_names(disposable_database) == [], (
        "enum types outlived their tables; the next upgrade will fail on 'type already exists'"
    )

    command.upgrade(config, "head")

    assert function_names(disposable_database) == sorted(FUNCTION_NAMES)
    assert enum_type_names(disposable_database) == sorted(ENUM_TYPE_NAMES)


def schema_identifiers(url: str) -> list[str]:
    """Every constraint, index and enum type name the built schema holds."""

    async def _run() -> list[str]:
        conn = await asyncpg.connect(url)
        try:
            rows = await conn.fetch(
                "SELECT c.conname AS name FROM pg_constraint c "
                "JOIN pg_namespace n ON n.oid = c.connamespace WHERE n.nspname = 'public' "
                "UNION SELECT indexname FROM pg_indexes WHERE schemaname = 'public' "
                "UNION SELECT t.typname FROM pg_type t "
                "JOIN pg_namespace tn ON tn.oid = t.typnamespace "
                "WHERE t.typtype = 'e' AND tn.nspname = 'public'"
            )
            return sorted(row["name"] for row in rows)
        finally:
            await conn.close()

    return asyncio.run(_run())


#: Names the database holds that are never *declared* by that name in source.
#:
#: All three are the same case, which is why they belong together: a name the
#: naming convention produced from a shorter declared one — ``email_is_lowercase``
#: becomes ``ck_users_email_is_lowercase`` — plus alembic's own
#: ``alembic_version_pkc``. That is what the convention is for, so these are
#: exceptions to state rather than to discover.
#:
#: ``ck_users_email_is_lowercase`` was missing, and the test passed anyway. It
#: appears in source in exactly two places, both **prose**: a comment in an
#: unrelated migration explaining a historical double-render. A substring match
#: over file text cannot tell a declaration from a sentence about one, so tidying
#: that comment would have turned this red — and told the reader a 27-character
#: name had been truncated past 63 bytes. Found in review, not by the test.
UNSOURCED_IDENTIFIERS = frozenset(
    {
        "alembic_version_pkc",
        "ck_admin_users_revoker_implies_revocation",
        "ck_users_email_is_lowercase",
    }
)

SOURCE_ROOTS = (Path("src"), Path("migrations"))


def test_every_schema_identifier_appears_verbatim_in_source(
    disposable_database: str, make_alembic_config: ConfigFactory
) -> None:
    """Catches a **silently truncated** identifier, from any source.

    PostgreSQL's limit is 63 bytes and SQLAlchemy does not reject a longer name —
    it truncates and appends a deterministic hash, with no warning and no
    ``NOTICE``. The database then holds an identifier that appears nowhere in the
    repository, and the first ``op.drop_constraint`` written against the declared
    name fails with *constraint does not exist* — handed the wrong name by the
    very file somebody opened to look it up.

    Nothing else in the gate can see it: **``alembic check`` compares foreign
    keys by column signature, never by name**, and no other check reads
    constraint names at all. A 65-character key shipped this way through six
    green CI checks and a thirteen-way mutation batch, and a reviewer querying
    ``pg_constraint`` found it.

    ``test_no_declared_identifier_exceeds_the_postgresql_limit`` closes the same
    hole at declaration time by walking ``Base.metadata``. This one is wider on
    purpose: a name written directly into a **migration** and into no model is
    invisible to that test, and both migrations in M2 hand-write names.
    """
    command.upgrade(make_alembic_config(disposable_database), "head")

    source = "\n".join(
        path.read_text(encoding="utf-8", errors="ignore")
        for root in SOURCE_ROOTS
        for path in root.rglob("*.py")
    )

    # A **quoted** occurrence, not a bare substring. Every identifier this test
    # is meant to protect is declared as a string literal — `Index("ix_…")`,
    # `name=op.f("fk_…")`, an enum label in `ENUM_TYPES` — so requiring the
    # quotes demands a declaration and rejects a passing mention.
    #
    # The looser version passed on a name that appears only inside a comment, and
    # would have gone red the day somebody edited that comment. A test that
    # depends on prose is a test that reports on the prose.
    missing = [
        name
        for name in schema_identifiers(disposable_database)
        if name not in UNSOURCED_IDENTIFIERS and f'"{name}"' not in source
    ]

    assert missing == [], (
        "these identifiers exist in the database but appear nowhere in src/ or "
        f"migrations/ — most likely silently truncated past 63 bytes: {missing}"
    )
