"""M2 admin - declined_by, declined_at, and the common-language flag

Two unrelated additions, in one migration because they ship in one release.

WHY `declined_by` RATHER THAN REUSING `approved_by`
===================================================
`mentor_profiles` carries `approved_at` and `approved_by` and nothing for the
other outcome, so a decline had nowhere to record who made it. The cheap version
is to reuse the approve pair for both decisions — and a column named
`approved_by` holding the person who *declined* is a lie the next reader
believes. This schema has paid for that shape twice: `usage_count`, which read
as a maintained counter and was zero forever, and `updated_at`, which came to
mean "a sync ran" until `last_synced_at` took that job back.

**And it cannot be reconstructed later.** `usage_count` was deleted because it
was derivable — you can always recount education entries. Who declined an
application exists only at the moment of the decision. That is the line between
a column worth adding and one worth dropping.

A `mentor_status_events` table is the right end state, and is not this. One
transition needs two columns; a third transition — re-approval, suspension,
reinstatement — is when the pairs stop scaling and an append-only log earns its
place.

WHY `is_common` RATHER THAN A SMALLER TABLE
===========================================
`languages` holds 7,078 rows from ISO 639-3, which is a completeness registry
and not a picker: searching "english" returned twenty creoles. The flag marks
the 100 languages in CLDR's `modern` coverage tier — what consumer products
actually ship — so a picker can default to those while search still reaches
everything.

Replacing the table with those 100 was considered and rejected on a measurement:
it would delete Efik, Ibibio, Tiv, Kanuri, Idoma, Urhobo, Nupe, Gbagyi, Esan,
Ebira and Jukun. Every one a Nigerian language, on a platform for African
students. The flag costs one boolean; the deletion costs a coverage gap pointed
at our own users, and reverses the reasoning that put this table on 639-3 rather
than 639-1 in the first place.

`und` is excluded — "undetermined" is not a language. `pcm` is excluded by
decision: **CLDR does include it**, so that is this project's choice and not the
standard's, and it stays fully searchable.

The list is a literal because a migration must never fetch. It is regenerated by
`scripts/derive_common_languages.py`, and a test asserts the two still agree.

Revision ID: e7d1a94c2b60
Revises: b83f0e51d7a2
Create Date: 2026-08-09 17:20:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7d1a94c2b60"
down_revision: str | Sequence[str] | None = "b83f0e51d7a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: ISO 639-3 codes at CLDR "modern" coverage, less `und` and `pcm`.
#: Regenerate with `uv run python scripts/derive_common_languages.py`.
COMMON_LANGUAGES = (
    "afr", "aka", "amh", "ara", "asm", "aze", "bak", "bel",
    "ben", "bos", "bul", "cat", "ces", "chr", "chv", "cym",
    "dan", "deu", "dsb", "ell", "eng", "est", "eus", "fas",
    "fil", "fin", "fra", "gla", "gle", "glg", "guj", "hat",
    "hau", "heb", "hin", "hrv", "hsb", "hun", "hye", "ibo",
    "ind", "isl", "ita", "jav", "jpn", "kan", "kat", "kaz",
    "khm", "kir", "kok", "kor", "lao", "lav", "lit", "mal",
    "mar", "mkd", "mon", "msa", "mya", "nep", "nld", "nno",
    "nob", "nor", "ori", "pan", "pol", "por", "pus", "que",
    "roh", "ron", "rus", "shn", "sin", "slk", "slv", "snd",
    "som", "spa", "sqi", "srp", "swa", "swe", "tam", "tel",
    "tha", "tir", "tuk", "tur", "ukr", "urd", "uzb", "vie",
    "yor", "yue", "zho", "zul",
)  # fmt: skip


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "mentor_profiles", sa.Column("declined_at", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    op.add_column("mentor_profiles", sa.Column("declined_by", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_mentor_profiles_declined_by_users"),
        "mentor_profiles",
        "users",
        ["declined_by"],
        ["id"],
        # RESTRICT, matching `approved_by`: deleting the admin who made a
        # decision must not take the decision with them.
        ondelete="RESTRICT",
    )

    op.add_column(
        "languages",
        sa.Column("is_common", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    # Partial: the picker only ever asks for the true rows, and an index over
    # 7,078 rows to find 100 is worth a fraction of one over all of them.
    op.create_index(
        "ix_languages_common",
        "languages",
        ["display_name"],
        postgresql_where=sa.text("is_common"),
    )
    op.execute(
        sa.text("UPDATE languages SET is_common = true WHERE code_639_3 = ANY(:codes)").bindparams(
            sa.bindparam("codes", value=list(COMMON_LANGUAGES))
        )
    )


def downgrade() -> None:
    """Downgrade schema. Reversible without loss — both are additive."""
    op.drop_index("ix_languages_common", table_name="languages")
    op.drop_column("languages", "is_common")
    op.drop_constraint(
        op.f("fk_mentor_profiles_declined_by_users"), "mentor_profiles", type_="foreignkey"
    )
    op.drop_column("mentor_profiles", "declined_by")
    op.drop_column("mentor_profiles", "declined_at")
