"""M2 institutions - country nullable, and a last_synced_at stamp

Two columns, both consequences of ADR 0020 mirroring the hipolabs catalogue.

DEPARTURES FROM docs/edufurther-migration/
==========================================

**1. ``country_id`` becomes nullable**, where the package has
``country_code char(2) NOT NULL``. A mirrored row always carries a country —
hipolabs supplies ``alpha_two_code`` on all 10,257 records. A row a *user*
created by typing a name the catalogue does not hold has none, and an admin
supplies it during the ``pending_review`` pass. `NOT NULL` would make that row
unwriteable, so the alternative is asking the user for a field the review process
exists to fill.

**2. ``last_synced_at`` has no counterpart in the package**, which never
contemplated a mirror. It records when a row was last *seen upstream*, which
``updated_at`` cannot: an unchanged source moves no ``updated_at``, so a week
with no upstream changes is indistinguishable from a sync that stopped running.
That ambiguity is the exact objection ADR 0008 raised against mirroring, and this
column is ADR 0020's answer to it.

THE DOWNGRADE CAN REFUSE, AND SHOULD
====================================
Restoring ``NOT NULL`` fails if any manual institution has no country yet. That
is correct: the rows exist, the constraint says they may not, and inventing a
country to satisfy a downgrade would put a wrong one in the table. Resolve the
pending rows first.

Revision ID: 13688233ac14
Revises: 8fb6c26ead9d
Create Date: 2026-08-08 14:55:00.811835

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13688233ac14"
down_revision: str | Sequence[str] | None = "8fb6c26ead9d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "institutions", sa.Column("last_synced_at", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    op.alter_column("institutions", "country_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    State irreversibility here rather than silently recreating an empty column.
    A downgrade that loses data without saying so is worse than one that refuses.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("institutions", "country_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("institutions", "last_synced_at")
    # ### end Alembic commands ###
