"""Generate the reference-data migration for `countries` and `languages`.

Run this, review the output, commit it. Do not hand-edit the generated file —
edit this script and regenerate.

    uv run python scripts/generate_reference_seeds.py \
        --revision <12-hex> --down-revision <parent> --output migrations/versions/<name>.py
    uv run ruff format <output> && uv run ruff check --fix <output>

WHY THE ROWS ARE EMBEDDED RATHER THAN READ FROM A DATA FILE
-----------------------------------------------------------
A migration must produce the same result in January and in August. One that
reads an external file produces whatever that file says *at the time it runs*,
so a fresh environment and an existing one silently diverge the moment anybody
regenerates. Embedding the rows makes the revision the record.

The annual ISO refresh is therefore a NEW migration — rerun this script with a
new revision id — never an edit to one already shipped.

DATA SOURCE AND ATTRIBUTION
---------------------------
Rows are derived from `pycountry`, which packages the Debian `iso-codes`
database (https://salsa.debian.org/iso-codes-team/iso-codes), licensed
LGPL-2.1-or-later. `iso-codes` in turn publishes the ISO 3166-1 country codes
and the SIL-maintained ISO 639-3 language codes.

Languages are filtered to `type == "L"` (living) and `scope in {"I", "M"}`
(individual languages and macrolanguages), which is the set the migration
handoff specifies. Macrolanguages are kept deliberately: for "what languages do
you speak", `ara` is the right granularity and nobody should have to choose
between thirty Arabic variants in a dropdown.
"""

from __future__ import annotations

import argparse
import datetime as dt
from pathlib import Path

import pycountry

LIVING = "L"
INDIVIDUAL_AND_MACRO = frozenset({"I", "M"})

HEADER = '''"""reference data — countries and languages

GENERATED by scripts/generate_reference_seeds.py. Do not hand-edit; regenerate.

Seeds ISO 3166-1 countries and the living subset of ISO 639-3 languages. Both
are foreign-key targets — six columns across identity and profiles reference
countries(code), and user_languages references languages(code_639_3) — so they
must be complete before M1 loads a single row.

Rows are embedded rather than read from a file so that this revision produces
the same result whenever it runs. The annual ISO refresh is a new migration.

Derived from pycountry / Debian iso-codes (LGPL-2.1-or-later), which publishes
ISO 3166-1 and the SIL-maintained ISO 639-3 code sets.

Revision ID: {revision}
Revises: {down_revision}
Create Date: {created}

"""

# ruff: noqa: RUF001
#
# Seven language names contain characters ruff reports as ambiguous: U+02BC
# MODIFIER LETTER APOSTROPHE, U+2019 RIGHT SINGLE QUOTATION MARK, and U+01C0
# LATIN LETTER DENTAL CLICK. Each is the correct orthography for the language it
# names, and ASCII-folding them would publish a wrong name for a real people.
# (The characters are deliberately not quoted in this comment: doing so trips the
# same rule again, as RUF003.)
#
# Scoped to this generated file rather than added to per-file-ignores for
# migrations/: in a hand-written migration an ambiguous character really could be
# a homoglyph worth catching, and a rule switched off for a whole directory stops
# protecting the files that still need it.

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = {revision!r}
down_revision: str | Sequence[str] | None = {down_revision!r}
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Lightweight table constructs for bulk_insert. Deliberately not the ORM models:
# a migration must describe the schema as it was at this revision, and a model
# that changes later would silently rewrite history.
#
# `id` is deliberately absent: the rows below omit it and the column default
# generates one per row. Committing 7,327 literal UUIDs would add ~286 KB to this
# file, taking it past pre-commit's 500 KB ceiling — the same limit this file
# already hit once. Deriving them from the ISO code instead (uuid5) was rejected
# on principle: a surrogate computed from the natural key changes whenever ISO
# retires or reassigns a code, which is exactly the volatility a surrogate exists
# to absorb. Reference ids therefore differ per environment, and nothing may
# depend on a literal one — look up by code.
countries_table = sa.table(
    "countries",
    sa.column("code", sa.CHAR(2)),
    sa.column("code_alpha3", sa.CHAR(3)),
    sa.column("display_name", sa.Text),
)

languages_table = sa.table(
    "languages",
    sa.column("code_639_3", sa.CHAR(3)),
    sa.column("code_639_1", sa.CHAR(2)),
    sa.column("display_name", sa.Text),
)

# Bind-parameter headroom: PostgreSQL caps a single statement at 65,535. The
# larger insert is {language_count} rows x 3 columns = {language_params} parameters.
# Adding a fourth column to languages would reach {language_params_four}, still under the
# cap but no longer comfortably — split the insert if a fifth is ever needed.
'''

BODY = '''

def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "countries",
        # Surrogate primary key, like every other table (ADR 0014). The ISO code
        # keeps its own UNIQUE constraint and remains the human-facing key — it
        # is simply not what foreign keys store.
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuid_generate_v7()"), nullable=False),
        sa.Column("code", sa.CHAR(2), nullable=False),
        sa.Column("code_alpha3", sa.CHAR(3), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_countries"),
        # The alpha-2 code was the primary key until ADR 0014. It stays UNIQUE
        # and NOT NULL, so nothing about lookup-by-code changes; what changes is
        # that a referencing row stores the id instead.
        sa.UniqueConstraint("code", name="uq_countries_code"),
        # ISO guarantees alpha-3 is unique; nothing else here would. The seeded
        # rows satisfy it by construction, so the case this actually guards is the
        # annual refresh — a new migration, per this file's own rule — introducing
        # a duplicate that would otherwise be accepted silently.
        sa.UniqueConstraint("code_alpha3", name="uq_countries_code_alpha3"),
    )

    op.create_table(
        "languages",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuid_generate_v7()"), nullable=False),
        sa.Column("code_639_3", sa.CHAR(3), nullable=False),
        sa.Column("code_639_1", sa.CHAR(2), nullable=True),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_languages"),
        sa.UniqueConstraint("code_639_3", name="uq_languages_code_639_3"),
        # Unique only where present. PostgreSQL treats nulls as distinct in a
        # UNIQUE constraint, which is exactly what this table needs: 6,904 of
        # 7,078 rows have no two-letter code and all of them must remain valid.
        sa.UniqueConstraint("code_639_1", name="uq_languages_code_639_1"),
    )

    # Attached per table, in the migration that creates the table. The handoff
    # used a blanket function that scanned every table in the schema; that is
    # non-deterministic across environments and invisible in a diff. The cost of
    # being explicit is that it can be forgotten, which is why a test asserts
    # every table carrying updated_at has this trigger.
    for table in ("countries", "languages"):
        op.execute(
            f"CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
        )

    op.bulk_insert(
        countries_table,
        [dict(zip(COUNTRIES_COLUMNS, row, strict=True)) for row in COUNTRIES],
    )
    op.bulk_insert(
        languages_table,
        [dict(zip(LANGUAGES_COLUMNS, row, strict=True)) for row in LANGUAGES],
    )


def downgrade() -> None:
    """Downgrade schema.

    Drops both tables, and the seeded rows with them. That is not data loss in
    the usual sense — every row is reproducible by re-running this revision — but
    anything referencing them by foreign key must already be gone, which is what
    dropping in reverse dependency order gives us for free here: nothing
    references these yet at this revision.
    """
    op.drop_table("languages")
    op.drop_table("countries")
'''


def country_rows() -> list[dict[str, str]]:
    return [
        {
            "code": country.alpha_2,
            "code_alpha3": country.alpha_3,
            "display_name": country.name,
        }
        for country in sorted(pycountry.countries, key=lambda c: c.alpha_2)
    ]


def language_rows() -> list[dict[str, str | None]]:
    living = [
        language
        for language in pycountry.languages
        if getattr(language, "type", None) == LIVING
        and getattr(language, "scope", None) in INDIVIDUAL_AND_MACRO
    ]
    return [
        {
            "code_639_3": language.alpha_3,
            "code_639_1": getattr(language, "alpha_2", None),
            "display_name": language.name,
        }
        for language in sorted(living, key=lambda language: language.alpha_3)
    ]


def render_rows(name: str, columns: tuple[str, ...], rows: list[dict[str, str | None]]) -> str:
    """Emit rows as tuples, with the column names stated once.

    Dict literals per row were the obvious first choice and produced a 561 KB
    file — every key repeated 7,078 times, which trips pre-commit's 500 KB limit.
    The fix is the representation, not the limit: a gate raised to admit an
    artefact is a gate that no longer holds for the next one.
    """
    lines = [f"{name}_COLUMNS = {columns!r}", f"{name} = ["]
    lines.extend("    " + repr(tuple(row[column] for column in columns)) + "," for row in rows)
    lines.append("]")
    return "\n".join(lines)


def render(revision: str, down_revision: str, created: str) -> str:
    countries = country_rows()
    languages = language_rows()
    header = HEADER.format(
        revision=revision,
        down_revision=down_revision,
        created=created,
        language_count=len(languages),
        language_params=len(languages) * 3,
        language_params_four=len(languages) * 4,
    )
    return "\n".join(
        [
            header,
            render_rows("COUNTRIES", ("code", "code_alpha3", "display_name"), countries),
            "",
            render_rows("LANGUAGES", ("code_639_3", "code_639_1", "display_name"), languages),
            BODY,
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--revision", required=True, help="new revision id (12 hex chars)")
    parser.add_argument("--down-revision", required=True, help="parent revision id")
    parser.add_argument("--output", required=True, type=Path, help="migration file to write")
    # Regenerating an existing revision must produce a file that differs only by
    # the change you made to this script. With the timestamp taken from the clock,
    # every regeneration also rewrites the header, so the diff can no longer be
    # read as "only my change" — which is the whole point of "edit the script and
    # regenerate" rather than hand-editing.
    parser.add_argument(
        "--created",
        default=None,
        help="Create Date header; pass the existing value when regenerating a shipped revision",
    )
    args = parser.parse_args()

    created = args.created or dt.datetime.now(tz=dt.UTC).strftime("%Y-%m-%d %H:%M:%S.%f")
    args.output.write_text(
        render(args.revision, args.down_revision, created), encoding="utf-8", newline="\n"
    )

    countries = len(country_rows())
    languages = len(language_rows())
    print(f"wrote {args.output}")
    print(f"  countries: {countries}")
    print(f"  languages: {languages}")
    print("now run: uv run ruff format <file> && uv run ruff check --fix <file>")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
